### PR TITLE
Attempt to fix unfocus.

### PR DESCRIPTION
**Pull request by iago-lito**
Here is an attempt to fix the focus problem introduced by #3. FWIU, calls to `inhibit_unfocus()` and `uninhibit_unfocus()` need to be exactly matched (?). This modification takes care of that. Maybe this'll solve the problem?

/!\ WIP I haven't actually tested it yet. I'll test it asap.

### CODE REVIEW

**Comment by iago-lito** [comment]
Well, this does not seem to work @elcste. I'm not sure I understand why it's broken or what to do to fix it then :(

**Comment by iago-lito** [comment]
Considering that I have been unable to preserve the original behaviour wrt focus, I'm very okay with the reversion.
I wish I could read more about this `inhibit_unfocus` logic, but damn, the dev-documentation for gnome *really* are cryptic :(

I don't think it is a good idea to submit my fork to EGO though, as it is a perfect way towards confusion for everyone. Instead, I can offer to maintain an 'official branch' `timer` here, and commit to keeping it in sync by rebasing atop your `main` whenever it updates. The README would explain the situation and offer to `git clone --branch timer https://github.com/elcste/hide-cursor ~/.local/share/gnome-shell/extensions` to get the alternative version.

This avoids duplicating the extension and having to invent/deal with variations around the name `hide-cursor*`. Also, it makes it very straightforward to re-unite both versions into one the day we eventually figure how to fix focus. What do you think? :)

**Comment by elcste** [comment]
That sounds good. 

I'm a fairly beginning git user so maybe you can heklp. Do you see any problem with me just creating a new commit to go back to my version? And then I can create the new branch and merge your PR in that.

**Comment by elcste** [comment]
I decided to do what I could personally easily understand, even if it was not optimal.

To do as you suggested above, you can create a PR  and then I can create a new branch `timer` and merge the PR to that? Or am I missing something (likely ;-) )?

**Comment by iago-lito** [comment]
Sure, I understand that you prefer not to rebase. Do whatever you're confident with, then I'll rebase the timer fix on top of that and PR against `timer` :)

**Comment by elcste** [comment]
Voilà: https://github.com/elcste/hide-cursor/tree/timer

**Comment by iago-lito** [comment]
There you go #7 ;)

**Comment by iago-lito** [comment]
(reopening after accidental deletion of `unfocus` branch)

**Comment by elcste** [comment]
@iago-lito The **Reopen** button has is disabled with the message *The unfocus brand was force-pushed or recreated.* :-(

**Pull request closed without merging**
